### ISSUE TITLE
真·公告 - Amemei.github.io

### ISSUE THREAD

**Issue by SuSWhW** [SuSWhW/Amemei.github.io-comment#6]
https://amemei.github.io/2023/02/21/%E7%9C%9F%C2%B7%E5%85%AC%E5%91%8A/ 

 
关于苍蓝星魔改
  最近很多人都在催我修苍蓝星的魔改...

**Comment by stan1998chen** [comment]
魔改难度有点高哦，进度一直卡在初始，有修改器吗？？？

**Comment by SuSWhW** [comment]
> 魔改难度有点高哦，进度一直卡在初始，有修改器吗？？？

有，我丢下载板块里
