### ISSUE TITLE
下载 - Amemei.github.io

### ISSUE THREAD

**Issue by SuSWhW** [SuSWhW/Amemei.github.io-comment#7]
https://amemei.github.io/2023/02/22/%E4%B8%8B%E8%BD%BD/ 

 苍蓝星魔改

**Comment by 100est001** [comment]
哦哦，找到了

**Comment by 2819944012** [comment]
乐园解压完后joi打不开

**Comment by SuSWhW** [comment]
> 乐园解压完后joi打不开

这是unity游戏，得在电脑上玩

**Comment by SuSWhW** [comment]
> 大佬想要仙肴圣餐的下载

彳亍，我稍后传

**Comment by SuSWhW** [comment]
> 大佬想要仙肴圣餐的下载

上了

**Comment by 3320655107** [comment]
大佬大佬，命中注定的召唤术也可以放下载链接嘛

**Comment by SuSWhW** [comment]
> 大佬大佬，命中注定的召唤术也可以放下载链接嘛

最近微软有那个大病把我E5强制过期了，所以最近是放不了的

**Comment by 3320655107** [comment]
> @SuSWhW
> > 大佬大佬，命中注定的召唤术也可以放下载链接嘛
> 
> 最近微软有那个大病把我E5强制过期了，所以最近是放不了的


> @SuSWhW
> > 大佬大佬，命中注定的召唤术也可以放下载链接嘛
> 
> 最近微软有那个大病把我E5强制过期了，所以最近是放不了的

嗯，谢谢大佬～

**Comment by tuzhuyue** [comment]
等命中注定召唤术ing

**Comment by giao6794** [comment]
所以说这里有些游戏是没法下载了么

**Comment by SuSWhW** [comment]
> 所以说这里有些游戏是没法下载了么

是

**Comment by JakeFYT** [comment]
docker hub需要如何使用？

**Comment by SuSWhW** [comment]
> docker hub需要如何使用？

点链接改后缀就行了

**Comment by SuSWhW** [comment]
> docker hub需要如何使用？

docker hub指的是下载源

**Comment by a0960757675** [comment]
我註冊完docker hub了，那要怎麼下載遊戲，點連結沒有反應

**Comment by sbxyr-9908** [comment]
emmm，链接403咋办，挂了梯子也上不去

**Comment by giao6794** [comment]
这个新的下载链接怎么用，全部复制进不去网站

**Comment by SuSWhW** [comment]
> 我註冊完docker hub了，那要怎麼下載遊戲，點連結沒有反應

不用注册，直接点链接就完事了，复制到浏览器打开

**Comment by SuSWhW** [comment]
> docker hub的链接都失效了啊

是，换百度了，之前老有人说docker hub没法用

**Comment by MainRelease** [comment]
评论是怎么实现的

**Comment by SuSWhW** [comment]
> 评论是怎么实现的

通过github的issue系统

**Comment by massuar** [comment]
大佬 仙药圣餐我咋没找到哪里下载 叫什么的呀

**Comment by SuSWhW** [comment]
> 大佬 仙药圣餐我咋没找到哪里下载 叫什么的呀

啊这，我忘传了，等我有时间就传

**Comment by MOSYMOZY** [comment]
大佬啊，最近秒传短链好像全寄了，能把短链换成长链吗？

**Comment by SuSWhW** [comment]
> 大佬啊，最近秒传短链好像全寄了，能把短链换成长链吗？

彳亍，我有空就换

**Comment by SuSWhW** [comment]
> 大佬啊，最近秒传短链好像全寄了，能把短链换成长链吗？

换了

**Comment by MOSYMOZY** [comment]
万华镜3改后缀显示.7z文件损坏是什么鬼？

**Comment by SuSWhW** [comment]
> 万华镜3改后缀显示.7z文件损坏是什么鬼？

？？？这是分卷压缩，直接把所有7z文件放在同一个目录下打开7z.001就好了

**Comment by MOSYMOZY** [comment]
> @SuSWhW
> > 万华镜3改后缀显示.7z文件损坏是什么鬼？
> 
> ？？？这是分卷压缩，直接把所有7z文件放在同一个目录下打开7z.001就好了

亻亍

**Comment by 2819944012** [comment]
下载的这个链接手机能用吗

**Comment by SuSWhW** [comment]
> 下载的这个链接手机能用吗

你可以找个百度秒传解析

**Comment by 2819944012** [comment]
> @SuSWhW
> > 下载的这个链接手机能用吗
> 
> 你可以找个百度秒传解析

emmmm，难搞

**Comment by giao6794** [comment]
大佬报错404怎么整

**Comment by SuSWhW** [comment]
> 大佬解析链接报错404怎么整

百度的锅，找找其他的秒传解析罢

**Comment by giao6794** [comment]
> @SuSWhW
> > 大佬解析链接报错404怎么整
> 
> 百度的锅，找找其他的秒传解析罢

换了之后变成报错2

**Comment by MOSYMOZY** [comment]
> @giao6794
> > @SuSWhW
> > > 大佬解析链接报错404怎么整
> > 
> > 百度的锅，找找其他的秒传解析罢
> 
> 换了之后变成报错2

链接貌似又寄了

**Comment by MOSYMOZY** [comment]
大佬换了三个解析都显示报错2咋回事？

**Comment by giao6794** [comment]
还有比基尼铠甲如果适配没做好就上传到下载吧

**Comment by SuSWhW** [comment]
> 还有比基尼铠甲如果适配没做好就上传到下载吧

那个不是我在维护，我也没办法
