### ISSUE TITLE
玩的 - Amemei.github.io

### ISSUE THREAD

**Issue by SuSWhW** [SuSWhW/Amemei.github.io-comment#8]
https://amemei.github.io/2023/04/09/%E7%8E%A9%E7%9A%84/ 

  公告
 注意事项
本站某些游戏作品可能存在但不限于违...

**Comment by 2997963223** [comment]
这是怎么做到的啊？！我这个门外汉完全不知道怎么实现云游戏....而且还怪流畅地...

**Comment by SuSWhW** [comment]
> @2997963223
> 这是怎么做到的啊？！我这个门外汉完全不知道怎么实现云游戏....而且还怪流畅地...

看看说点什么那个板块，里面有讲

**Comment by pimanhub** [comment]
光与影什么时候再上啊？

**Comment by SuSWhW** [comment]
> 光与影什么时候再上啊？

那玩意儿依赖本地的nodejs运行环境，没法在网页运行
