### ISSUE TITLE
说点什么 - Amemei.github.io

### ISSUE THREAD

**Issue by SuSWhW** [SuSWhW/Amemei.github.io-comment#9]
https://amemei.github.io/2023/05/01/%E8%AF%B4%E7%82%B9%E4%BB%80%E4%B9%88/ 

  紧急通知
我给部分游戏的网站绑定了域名，然后忘记了更...

**Comment by 100est001** [comment]
呃，我找到一些黄油有html的，能发给你吗？

**Comment by SuSWhW** [comment]
> 呃，我找到一些黄油有html的，能发给你吗？

好啊，欢迎

**Comment by SuSWhW** [comment]
> 呃，我找到一些黄油有html的，能发给你吗？

你可以先截个图让我看看文件结构

**Comment by 100est001** [comment]
> @SuSWhW
> > 呃，我找到一些黄油有html的，能发给你吗？
> 
> 你可以先截个图让我看看文件结构

**Comment by 100est001** [comment]
![Uploading Screenshot_2023-05-10-01-06-04-65_55bef12f624c2b805189a6aa783c400d.jpg…]()

**Comment by 100est001** [comment]
> @SuSWhW
> > 呃，我找到一些黄油有html的，能发给你吗？
> 
> 你可以先截个图让我看看文件结构

发哪里呀

**Comment by SuSWhW** [comment]
> > @SuSWhW
> > > 呃，我找到一些黄油有html的，能发给你吗？
> > 
> > 
> > 你可以先截个图让我看看文件结构
> 
> 发哪里呀

可以发我邮箱`q78kg.1ffrj6@outlook.com`

也可以在`https://github.com/SuSWhW/Amemei.github.io-comment/issues/9`这里发，评论系统的图片上传是有问题的，所以只能这样

**Comment by promissame** [comment]
那现在git的下载寄了怎么下游戏勒（（（

**Comment by SuSWhW** [comment]
> 那现在git的下载寄了怎么下游戏勒（（（

（（（，我E5也寄了，我发个微云罢

**Comment by SuSWhW** [comment]
> 那现在git的下载寄了怎么下游戏勒（（（

等罢（
